import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto'
import { promisify } from 'node:util'
import { createServer } from 'node:http'
import { createReadStream, existsSync, mkdirSync } from 'node:fs'
import { stat, writeFile, unlink } from 'node:fs/promises'
import { extname, resolve, sep } from 'node:path'
import { all, databasePath, id, now, one, run, transaction } from './db.mjs'

const scrypt = promisify(scryptCallback)
const port = Number(process.env.PORT || process.env.LEARNLY_API_PORT || 8787)
const sessionDays = 7
const passwordResetMinutes = 30
const passwordMinimumLength = 10
// Demo data is never enabled by the npm command name. Production must opt in explicitly.
const demoMode = process.env.NODE_ENV === 'development' || process.env.LEARNLY_ENABLE_DEMO === 'true'
const resetRateLimits = new Map()
const distDirectory = resolve('dist')
const uploadDirectory = resolve(process.env.LEARNLY_UPLOAD_DIR || 'data/uploads')
mkdirSync(uploadDirectory, { recursive: true })
const uploadLimits = { video: Number(process.env.LEARNLY_VIDEO_MAX_BYTES || 500 * 1024 * 1024), notes: Number(process.env.LEARNLY_NOTES_MAX_BYTES || 20 * 1024 * 1024), material: Number(process.env.LEARNLY_MATERIAL_MAX_BYTES || 20 * 1024 * 1024) }
const assetRules = { video: { extensions: ['.mp4', '.webm', '.mov'], mimes: ['video/mp4', 'video/webm', 'video/quicktime'] }, notes: { extensions: ['.pdf', '.txt'], mimes: ['application/pdf', 'text/plain'] }, material: { extensions: ['.pdf'], mimes: ['application/pdf'] } }
const mimeTypes = {
  '.css': 'text/css; charset=utf-8', '.html': 'text/html; charset=utf-8', '.ico': 'image/x-icon',
  '.js': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8', '.png': 'image/png', '.svg': 'image/svg+xml',
  '.webp': 'image/webp', '.woff': 'font/woff', '.woff2': 'font/woff2',
}
const demoPassword = 'Learnly-local-demo-password-2026'
const demoAccounts = {
  teacher: { email: 'demo.teacher@learnly.local', displayName: 'Demo Teacher', classLevel: null },
  admin: { email: 'demo.admin@learnly.local', displayName: 'Demo Admin', classLevel: null },
}
const demoStudents = [
  { email: 'demo.student.c8@learnly.local', displayName: 'Demo Student (Class 8)', classLevel: 8 },
  { email: 'demo.student.c9@learnly.local', displayName: 'Demo Student (Class 9)', classLevel: 9 },
  { email: 'demo.student.c10@learnly.local', displayName: 'Demo Student (Class 10)', classLevel: 10 },
]
const json = (response, status, body) => { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(body)) }
const hashToken = (token) => createHash('sha256').update(token).digest('hex')
const normalizeEmail = (email) => String(email || '').trim().toLowerCase()
const deviceLabel = (request) => String(request.headers['user-agent'] || 'Unknown device').slice(0, 160)
const clientAddress = (request) => String(request.socket.remoteAddress || 'unknown')
const parseCookies = (request) => Object.fromEntries(String(request.headers.cookie || '').split(';').map((part) => part.trim().split('=').map(decodeURIComponent)).filter(([key]) => key))
const readJson = async (request) => new Promise((resolve, reject) => { let value = ''; request.on('data', (chunk) => { value += chunk; if (value.length > 1_000_000) reject(new Error('Request too large')) }); request.on('end', () => { try { resolve(value ? JSON.parse(value) : {}) } catch { reject(new Error('Invalid JSON')) } }) })
const readMultipart = async (request, limit) => new Promise((resolve, reject) => { const chunks = []; let size = 0; request.on('data', (chunk) => { size += chunk.length; if (size > limit) { reject(new Error('Upload exceeds the configured size limit.')); request.destroy() } else chunks.push(chunk) }); request.on('end', () => resolve(Buffer.concat(chunks))); request.on('error', reject) })
function multipartFile(buffer, contentType) { const match = /boundary=([^;]+)/i.exec(contentType || ''); if (!match) throw new Error('Expected multipart/form-data.'); const boundary = Buffer.from(`--${match[1].replaceAll('"', '')}`); const start = buffer.indexOf(Buffer.from('\r\n\r\n')); if (start < 0) throw new Error('Invalid upload.'); const headers = buffer.subarray(0, start).toString('utf8'); const filename = /filename="([^"]*)"/i.exec(headers)?.[1]; const mime = /content-type:\s*([^\r\n]+)/i.exec(headers)?.[1]?.trim().toLowerCase() || 'application/octet-stream'; const end = buffer.lastIndexOf(boundary); if (!filename || end < start) throw new Error('Choose a file to upload.'); return { filename: filename.replace(/[\\/\0]/g, '_').slice(0, 180), mime, content: buffer.subarray(start + 4, end - 2) } }
function hasExpectedAssetSignature(assetType, extension, content) { if (extension === '.pdf') return content.subarray(0, 5).toString('ascii') === '%PDF-'; if (extension === '.txt') return !content.subarray(0, 4096).includes(0); if (extension === '.mp4' || extension === '.mov') return content.length > 12 && content.subarray(4, 8).toString('ascii') === 'ftyp'; if (extension === '.webm') return content.subarray(0, 4).equals(Buffer.from([0x1a, 0x45, 0xdf, 0xa3])); return false }
function lessonForUser(lessonId, user) { const lesson = one('SELECT l.id,l.status,c.class_level,c.published,c.teacher_id FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE l.id=?', lessonId); if (!lesson) return null; if (user.role === 'admin' || (user.role === 'teacher' && lesson.teacher_id === user.id)) return lesson; if (user.role === 'student' && lesson.status === 'published' && lesson.published && lesson.class_level === user.classLevel && (!one('SELECT 1 FROM lesson_assignments WHERE lesson_id=? LIMIT 1', lessonId) || one('SELECT 1 FROM lesson_assignments WHERE lesson_id=? AND student_id=?', lessonId, user.id))) return lesson; return null }
function canUseConversation(user, conversation) { if (user.role === 'admin') return true; return Boolean(one('SELECT 1 FROM conversation_participants WHERE conversation_id=? AND user_id=?', conversation.id, user.id)) || (user.role === 'student' && conversation.student_id === user.id) || (user.role === 'teacher' && conversation.teacher_id === user.id) }

async function hashPassword(password) { const salt = randomBytes(16).toString('hex'); const derived = await scrypt(password, salt, 64); return `scrypt$${salt}$${Buffer.from(derived).toString('hex')}` }
async function verifyPassword(password, stored) { const [, salt, expected] = String(stored).split('$'); if (!salt || !expected) return false; const actual = Buffer.from(await scrypt(password, salt, 64)); const wanted = Buffer.from(expected, 'hex'); return actual.length === wanted.length && timingSafeEqual(actual, wanted) }
function withinResetRateLimit(key, limit = 5) { const windowStart = Date.now() - 15 * 60_000; const attempts = (resetRateLimits.get(key) || []).filter((time) => time > windowStart); if (attempts.length >= limit) { resetRateLimits.set(key, attempts); return false }; attempts.push(Date.now()); resetRateLimits.set(key, attempts); return true }
function resetExpiry() { return new Date(Date.now() + passwordResetMinutes * 60_000).toISOString() }
function createPasswordReset(userId, request, initiatedByUserId = null) { const token = randomBytes(32).toString('base64url'); const createdAt = now(); transaction(() => { run('UPDATE password_reset_tokens SET used_at=? WHERE user_id=? AND used_at IS NULL', createdAt, userId); run('INSERT INTO password_reset_tokens (id,user_id,token_hash,created_at,expires_at,used_at,initiated_by_user_id) VALUES (?,?,?,?,?,?,?)', id(), userId, hashToken(token), createdAt, resetExpiry(), null, initiatedByUserId) }); event(userId, initiatedByUserId ? 'admin_password_reset_initiated' : 'password_reset_requested', request, initiatedByUserId ? 'Password reset initiated by an administrator.' : 'Password reset requested.'); return token }
async function seedDemoAccounts() {
  if (!demoMode) return
  for (const [role, demo] of Object.entries(demoAccounts)) {
    if (one('SELECT id FROM users WHERE email=?', demo.email)) continue
    const timestamp = now(); const userId = id(); const passwordHash = await hashPassword(demoPassword)
    transaction(() => { run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', userId, role, demo.email, demo.displayName, demo.classLevel, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', userId, passwordHash, timestamp) })
  }
  for (const demo of demoStudents) {
    if (one('SELECT id FROM users WHERE email=?', demo.email)) continue
    const timestamp = now(); const userId = id(); const passwordHash = await hashPassword(demoPassword)
    transaction(() => { run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', userId, 'student', demo.email, demo.displayName, demo.classLevel, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', userId, passwordHash, timestamp) })
  }
  const teacher = one('SELECT id FROM users WHERE email=?', demoAccounts.teacher.email)
  if (teacher && !one('SELECT id FROM courses WHERE teacher_id=? LIMIT 1', teacher.id)) {
    const timestamp = now(); const courseId = id(); const chapterId = id(); const lessonId = id()
    transaction(() => { run('INSERT INTO courses VALUES (?,?,?,?,?,?,?,?)', courseId, 'Demo Mathematics · Class 8', 'mathematics', 8, teacher.id, 'A development-only sample course.', 1, timestamp); run('INSERT INTO chapters VALUES (?,?,?,?,?)', chapterId, courseId, 'Demo chapter', 'A sample chapter for local testing.', 1); run('INSERT INTO lessons (id,chapter_id,title,description,video_label,notes_label,material_label,content,status,position,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', lessonId, chapterId, 'Demo published lesson', 'A sample lesson visible to the Demo Student.', 'Demo video placeholder', 'Demo notes', 'Demo worksheet', 'This development-only lesson confirms the student access flow.', 'published', 1, timestamp) })
  }
}
async function bootstrapConfiguredAdmin() {
  const email = normalizeEmail(process.env.ADMIN_EMAIL)
  const password = String(process.env.ADMIN_PASSWORD || '')
  const name = String(process.env.ADMIN_NAME || 'Platform Administrator').trim()
  if (one("SELECT id FROM users WHERE role='admin'")) return
  if (!email && !password) return
  if (!email.includes('@') || password.length < 12) throw new Error('ADMIN_EMAIL and ADMIN_PASSWORD must be set together; ADMIN_PASSWORD must be at least 12 characters.')
  if (one('SELECT id FROM users WHERE email=?', email)) throw new Error('ADMIN_EMAIL is already assigned to a non-admin account.')
  const timestamp = now(); const userId = id(); const passwordHash = await hashPassword(password)
  transaction(() => { run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', userId, 'admin', email, name || 'Platform Administrator', null, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', userId, passwordHash, timestamp) })
  console.log('Configured first admin created.')
}
function publicUser(user) { return { id: user.id, role: user.role, email: user.email, displayName: user.display_name, classLevel: user.class_level, accessState: user.access_state } }
function event(userId, type, request, detail, sessionId) { run('INSERT INTO security_events (id,user_id,type,occurred_at,session_id,device_label,detail) VALUES (?,?,?,?,?,?,?)', id(), userId || null, type, now(), sessionId || null, deviceLabel(request), detail || null) }
function setSessionCookie(response, token, expires) { response.setHeader('Set-Cookie', `learnly_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${sessionDays * 86400}${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`) }
function clearSessionCookie(response) { response.setHeader('Set-Cookie', 'learnly_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0') }
function authenticate(request) { const token = parseCookies(request).learnly_session; if (!token) return null; const session = one(`SELECT s.*, u.id AS authenticated_user_id, u.role, u.email, u.display_name, u.class_level, u.access_state FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?`, hashToken(token), now()); if (!session || session.access_state !== 'active') return null; run('UPDATE sessions SET last_active_at=? WHERE id=?', now(), session.id); return { session, user: publicUser({ ...session, id: session.authenticated_user_id }) } }
function requireRole(request, response, roles) { const auth = authenticate(request); if (!auth) { json(response, 401, { error: 'Please log in to continue.' }); return null } if (!roles.includes(auth.user.role)) { json(response, 403, { error: 'You do not have permission for this action.' }); return null } return auth }
async function createSession(response, request, user) { const token = randomBytes(32).toString('base64url'); const createdAt = now(); const expiresAt = new Date(Date.now() + sessionDays * 86400_000).toISOString(); const sessionId = id(); run('INSERT INTO sessions VALUES (?,?,?,?,?,?,?,?,?,?)', sessionId, user.id, hashToken(token), deviceLabel(request), createdAt, createdAt, expiresAt, null, null, null); event(user.id, 'login_success', request, 'Successful login', sessionId); setSessionCookie(response, token, expiresAt); return { id: sessionId, deviceLabel: deviceLabel(request), createdAt, expiresAt } }

async function route(request, response) {
  if (request.method === 'OPTIONS') return json(response, 204, {})
  const url = new URL(request.url, `http://${request.headers.host}`); const path = url.pathname
  try {
    if (request.method === 'GET' && path === '/api/health') return json(response, 200, { status: 'ok', database: 'local-sqlite' })
    if (request.method === 'POST' && path === '/api/dev/demo-login') {
      if (!demoMode) return json(response, 404, { error: 'Route not found.' })
      const body = await readJson(request); const role = body.role; const classLevel = body.classLevel ? Number(body.classLevel) : null
      let email = null
      if (role === 'student') {
        const demo = demoStudents.find((s) => s.classLevel === classLevel)
        if (!demo) return json(response, 400, { error: 'Choose a valid class for the demo student.' })
        email = demo.email
      } else {
        const demo = demoAccounts[role]
        if (!demo) return json(response, 400, { error: 'Choose a demo account.' })
        email = demo.email
      }
      const user = one('SELECT u.*,c.password_hash FROM users u JOIN credentials c ON c.user_id=u.id WHERE u.email=?', email)
      if (!user || !(await verifyPassword(demoPassword, user.password_hash)) || user.access_state !== 'active') return json(response, 403, { error: 'This demo account is unavailable. Restart the local API to reseed missing accounts.' })
      const session = await createSession(response, request, user); return json(response, 200, { user: publicUser(user), session })
    }
    if (request.method === 'POST' && path === '/api/auth/register') {
      const body = await readJson(request); const email = normalizeEmail(body.email); const role = body.role; const classLevel = Number(body.classLevel)
      if (!['student', 'teacher'].includes(role) || !email.includes('@') || String(body.password || '').length < 10 || !String(body.displayName || '').trim()) return json(response, 400, { error: 'Enter a name, valid email, and a password with at least 10 characters.' })
      if (role === 'student' && ![8, 9, 10].includes(classLevel)) return json(response, 400, { error: 'Students must select Class 8, 9, or 10.' })
      if (one('SELECT id FROM users WHERE email=?', email)) return json(response, 409, { error: 'An account with this email already exists.' })
      const user = { id: id(), role, email, displayName: String(body.displayName).trim(), classLevel: role === 'student' ? classLevel : null }; const timestamp = now(); const passwordHash = await hashPassword(body.password)
      transaction(() => { run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', user.id, user.role, user.email, user.displayName, user.classLevel, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', user.id, passwordHash, timestamp) })
      const session = await createSession(response, request, { ...user, access_state: 'active', display_name: user.displayName, class_level: user.classLevel }); return json(response, 201, { user: { ...user, accessState: 'active' }, session })
    }
    if (request.method === 'POST' && path === '/api/auth/login') {
      const body = await readJson(request); const email = normalizeEmail(body.email); const user = one('SELECT u.*, c.password_hash FROM users u JOIN credentials c ON c.user_id=u.id WHERE u.email=?', email)
      if (!user || !(await verifyPassword(String(body.password || ''), user.password_hash))) { if (user) event(user.id, 'login_failed', request, 'Incorrect password'); return json(response, 401, { error: 'Incorrect email or password.' }) }
      if (user.access_state !== 'active') { event(user.id, 'access_denied', request, 'Login blocked by account access state'); return json(response, 403, { error: 'This account does not currently have access.' }) }
      const session = await createSession(response, request, user); return json(response, 200, { user: publicUser(user), session })
    }
    if (request.method === 'POST' && path === '/api/auth/password-reset/request') {
      const body = await readJson(request); const email = normalizeEmail(body.email); const rateKey = `request:${hashToken(`${clientAddress(request)}:${email}`)}`
      if (email && withinResetRateLimit(rateKey)) {
        const user = one('SELECT id,access_state FROM users WHERE email=?', email)
        if (user?.access_state === 'active') {
          const token = createPasswordReset(user.id, request)
          // Production delivery is intentionally external; tokens are never logged or persisted in plaintext.
          if (process.env.NODE_ENV === 'development') return json(response, 200, { message: 'If an account exists for that email, password reset instructions have been sent.', resetToken: token })
        }
      }
      return json(response, 200, { message: 'If an account exists for that email, password reset instructions have been sent.' })
    }
    if (request.method === 'POST' && path === '/api/auth/password-reset/confirm') {
      const body = await readJson(request); const token = String(body.token || ''); const password = String(body.password || ''); const rateKey = `confirm:${hashToken(`${clientAddress(request)}:${token}`)}`
      if (!withinResetRateLimit(rateKey, 10) || token.length < 32 || password.length < passwordMinimumLength) return json(response, 400, { error: 'This reset link is invalid or expired, or the password does not meet the minimum length.' })
      const reset = one(`SELECT id,user_id FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>?`, hashToken(token), now())
      if (!reset) return json(response, 400, { error: 'This reset link is invalid or expired, or the password does not meet the minimum length.' })
      const passwordHash = await hashPassword(password); const timestamp = now()
      transaction(() => { run('UPDATE credentials SET password_hash=?,password_changed_at=? WHERE user_id=?', passwordHash, timestamp, reset.user_id); run('UPDATE password_reset_tokens SET used_at=? WHERE id=?', timestamp, reset.id); run("UPDATE sessions SET revoked_at=?,revoke_reason='password_reset' WHERE user_id=? AND revoked_at IS NULL", timestamp, reset.user_id) })
      event(reset.user_id, 'password_reset_completed', request, 'Password reset completed; active sessions revoked.')
      return json(response, 200, { message: 'Password updated. Please log in with your new password.' })
    }
    if (request.method === 'POST' && path === '/api/auth/logout') { const auth = authenticate(request); if (auth) { run('UPDATE sessions SET revoked_at=?, revoke_reason=? WHERE id=?', now(), 'user_logout', auth.session.id); event(auth.user.id, 'logout', request, 'Logged out', auth.session.id) }; clearSessionCookie(response); return json(response, 200, { ok: true }) }
    if (request.method === 'GET' && path === '/api/auth/me') { const auth = authenticate(request); return auth ? json(response, 200, { user: auth.user }) : json(response, 200, { user: null }) }
    if (request.method === 'GET' && path === '/api/auth/admin-bootstrap-status') return json(response, 200, { available: !one("SELECT id FROM users WHERE role='admin'") })
    if (request.method === 'POST' && path === '/api/auth/bootstrap-admin') {
      if (one("SELECT id FROM users WHERE role='admin'")) return json(response, 403, { error: 'An admin already exists.' }); const body = await readJson(request); const setupKey = process.env.LEARNLY_ADMIN_SETUP_KEY
      if (!setupKey || body.setupKey !== setupKey) return json(response, 403, { error: 'Set LEARNLY_ADMIN_SETUP_KEY on the local server before creating the first admin.' })
      const email = normalizeEmail(body.email); if (!email.includes('@') || String(body.password || '').length < 12 || !String(body.displayName || '').trim()) return json(response, 400, { error: 'Enter a name, valid email, and a password with at least 12 characters.' })
      const timestamp = now(); const user = { id: id(), role: 'admin', email, displayName: String(body.displayName).trim(), classLevel: null }; const passwordHash = await hashPassword(body.password); transaction(() => { run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', user.id, user.role, user.email, user.displayName, null, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', user.id, passwordHash, timestamp) }); const session = await createSession(response, request, { ...user, access_state: 'active', display_name: user.displayName, class_level: null }); return json(response, 201, { user: { ...user, accessState: 'active' }, session })
    }
    if (request.method === 'GET' && path === '/api/admin/admins') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const admins = all("SELECT id,display_name AS displayName,email,created_at AS createdAt FROM users WHERE role='admin' ORDER BY created_at"); return json(response, 200, { admins, count: admins.length, maximum: 3 }) }
    if (request.method === 'POST' && path === '/api/admin/admins') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const body = await readJson(request); const email = normalizeEmail(body.email); const name = String(body.displayName || '').trim(); const password = String(body.password || ''); if (!name || !email.includes('@') || password.length < 12) return json(response, 400, { error: 'Enter a name, valid email, and a password with at least 12 characters.' }); const passwordHash = await hashPassword(password); let user; try { transaction(() => { const count = Number(one("SELECT COUNT(*) AS count FROM users WHERE role='admin'").count); if (count >= 3) throw new Error('ADMIN_LIMIT'); if (one('SELECT id FROM users WHERE email=?', email)) throw new Error('DUPLICATE_EMAIL'); user = { id: id(), role: 'admin', email, displayName: name }; const timestamp = now(); run('INSERT INTO users VALUES (?,?,?,?,?,?,?,?)', user.id, 'admin', email, name, null, 'active', timestamp, timestamp); run('INSERT INTO credentials VALUES (?,?,?)', user.id, passwordHash, timestamp) }) } catch (error) { return json(response, error.message === 'ADMIN_LIMIT' ? 409 : error.message === 'DUPLICATE_EMAIL' ? 409 : 500, { error: error.message === 'ADMIN_LIMIT' ? 'The maximum of 3 admins has been reached.' : error.message === 'DUPLICATE_EMAIL' ? 'An account with this email already exists.' : 'Could not create admin.' }) }; event(user.id, 'admin_created', request, `Created by admin ${auth.user.id}`); return json(response, 201, { admin: { id: user.id, displayName: user.displayName, email: user.email } }) }
    if (request.method === 'POST' && /^\/api\/teacher\/lessons\/[^/]+\/assets\/(video|notes|material)$/.test(path)) { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const [, lessonId, assetType] = /^\/api\/teacher\/lessons\/([^/]+)\/assets\/(video|notes|material)$/.exec(path); const lesson = lessonForUser(lessonId, auth.user); if (!lesson) return json(response, 404, { error: 'Lesson not found.' }); const raw = await readMultipart(request, uploadLimits[assetType] + 256 * 1024); const file = multipartFile(raw, request.headers['content-type']); const ext = extname(file.filename).toLowerCase(); const rule = assetRules[assetType]; if (!rule.extensions.includes(ext) || !rule.mimes.includes(file.mime) || !hasExpectedAssetSignature(assetType, ext, file.content) || file.content.length > uploadLimits[assetType]) return json(response, 400, { error: 'Unsupported file type or file exceeds the configured size limit.' }); const storedFilename = `${id()}${ext}`; const filePath = resolve(uploadDirectory, storedFilename); if (!filePath.startsWith(`${uploadDirectory}${sep}`)) return json(response, 400, { error: 'Invalid file name.' }); await writeFile(filePath, file.content, { mode: 0o640 }); const old = one('SELECT * FROM lesson_assets WHERE lesson_id=? AND asset_type=?', lessonId, assetType); const urlColumn = assetType === 'material' ? 'material_url' : `${assetType}_url`; const labelColumn = assetType === 'material' ? 'material_label' : `${assetType}_label`; try { transaction(() => { run('DELETE FROM lesson_assets WHERE lesson_id=? AND asset_type=?', lessonId, assetType); run('INSERT INTO lesson_assets VALUES (?,?,?,?,?,?,?,?,?)', id(), lessonId, auth.user.id, assetType, file.filename, storedFilename, file.mime, file.content.length, now()); run(`UPDATE lessons SET ${labelColumn}=?,${urlColumn}=? WHERE id=?`, file.filename, `/api/assets/${lessonId}/${assetType}`, lessonId) }) } catch (error) { await unlink(filePath).catch(() => undefined); throw error } if (old) await unlink(resolve(uploadDirectory, old.stored_filename)).catch(() => undefined); return json(response, 201, { asset: { type: assetType, filename: file.filename, size: file.content.length, url: `/api/assets/${lessonId}/${assetType}` } }) }
    if (request.method === 'DELETE' && /^\/api\/teacher\/lessons\/[^/]+\/assets\/(video|notes|material)$/.test(path)) { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const [, lessonId, assetType] = /^\/api\/teacher\/lessons\/([^/]+)\/assets\/(video|notes|material)$/.exec(path); if (!lessonForUser(lessonId, auth.user)) return json(response, 404, { error: 'Lesson not found.' }); const asset = one('SELECT * FROM lesson_assets WHERE lesson_id=? AND asset_type=?', lessonId, assetType); if (!asset) return json(response, 404, { error: 'File not found.' }); const urlColumn = assetType === 'material' ? 'material_url' : `${assetType}_url`; const labelColumn = assetType === 'material' ? 'material_label' : `${assetType}_label`; transaction(() => { run('DELETE FROM lesson_assets WHERE id=?', asset.id); run(`UPDATE lessons SET ${labelColumn}='',${urlColumn}='' WHERE id=?`, lessonId) }); await unlink(resolve(uploadDirectory, asset.stored_filename)).catch(() => undefined); return json(response, 200, { ok: true }) }
    if (request.method === 'GET' && /^\/api\/assets\/[^/]+\/(video|notes|material)$/.test(path)) { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const [, lessonId, assetType] = /^\/api\/assets\/([^/]+)\/(video|notes|material)$/.exec(path); if (!lessonForUser(lessonId, auth.user)) return json(response, 404, { error: 'File not found.' }); const asset = one('SELECT * FROM lesson_assets WHERE lesson_id=? AND asset_type=?', lessonId, assetType); if (!asset) return json(response, 404, { error: 'File not found.' }); const filePath = resolve(uploadDirectory, asset.stored_filename); if (!filePath.startsWith(`${uploadDirectory}${sep}`) || !existsSync(filePath)) return json(response, 404, { error: 'File not found.' }); response.writeHead(200, { 'Content-Type': asset.mime_type, 'Content-Length': asset.size, 'Content-Disposition': `inline; filename="${asset.original_filename.replace(/["\\\r\n]/g, '_')}"`, 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'private, no-store' }); return createReadStream(filePath).pipe(response) }
    if (request.method === 'GET' && path === '/api/notices') { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const notices = auth.user.role === 'admin' ? all('SELECT n.*,u.display_name AS author FROM notices n JOIN users u ON u.id=n.created_by ORDER BY n.created_at DESC') : auth.user.role === 'student' ? all('SELECT n.*,u.display_name AS author FROM notices n JOIN users u ON u.id=n.created_by WHERE n.target_class IS NULL OR n.target_class=? ORDER BY n.created_at DESC', auth.user.classLevel) : all('SELECT n.*,u.display_name AS author FROM notices n JOIN users u ON u.id=n.created_by WHERE n.target_class IS NULL OR EXISTS (SELECT 1 FROM courses c WHERE c.teacher_id=? AND c.class_level=n.target_class) ORDER BY n.created_at DESC', auth.user.id); return json(response, 200, { notices }) }
    if (request.method === 'POST' && path === '/api/admin/notices') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const body = await readJson(request); const title = String(body.title || '').trim(); const content = String(body.content || '').trim(); const target = body.targetClass === '' || body.targetClass == null ? null : Number(body.targetClass); if (!title || !content || title.length > 160 || content.length > 5000 || (target !== null && ![8,9,10].includes(target))) return json(response, 400, { error: 'Enter a valid title, notice, and target class.' }); const timestamp = now(); const notice = { id: id(), title, content, targetClass: target, createdAt: timestamp, updatedAt: timestamp }; run('INSERT INTO notices VALUES (?,?,?,?,?,?,?)', notice.id, title, content, target, auth.user.id, timestamp, timestamp); return json(response, 201, { notice }) }
    if (request.method === 'PATCH' && /^\/api\/admin\/notices\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const body = await readJson(request); const noticeId = path.split('/')[4]; const title = String(body.title || '').trim(); const content = String(body.content || '').trim(); const target = body.targetClass === '' || body.targetClass == null ? null : Number(body.targetClass); if (!title || !content || title.length > 160 || content.length > 5000 || (target !== null && ![8,9,10].includes(target))) return json(response, 400, { error: 'Enter a valid title, notice, and target class.' }); const result = run('UPDATE notices SET title=?,content=?,target_class=?,updated_at=? WHERE id=?', title, content, target, now(), noticeId); return result.changes ? json(response, 200, { ok: true }) : json(response, 404, { error: 'Notice not found.' }) }
    if (request.method === 'DELETE' && /^\/api\/admin\/notices\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const result = run('DELETE FROM notices WHERE id=?', path.split('/')[4]); return result.changes ? json(response, 200, { ok: true }) : json(response, 404, { error: 'Notice not found.' }) }
    if (request.method === 'GET' && path === '/api/chat/conversations') { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const where = auth.user.role === 'admin' ? '' : auth.user.role === 'student' ? 'WHERE c.student_id=?' : 'WHERE c.teacher_id=?'; const params = auth.user.role === 'admin' ? [] : [auth.user.id]; const conversations = all(`SELECT c.id,c.student_id AS studentId,c.teacher_id AS teacherId,c.updated_at AS updatedAt,s.display_name AS studentName,t.display_name AS teacherName,(SELECT body FROM messages WHERE conversation_id=c.id ORDER BY created_at DESC LIMIT 1) AS lastMessage,(SELECT COUNT(*) FROM messages WHERE conversation_id=c.id AND sender_id<>? AND read_at IS NULL) AS unread FROM conversations c JOIN users s ON s.id=c.student_id LEFT JOIN users t ON t.id=c.teacher_id ${where} ORDER BY c.updated_at DESC`, auth.user.id, ...params); return json(response, 200, { conversations }) }
    if (request.method === 'GET' && path === '/api/chat/teachers') { const auth = requireRole(request, response, ['student']); if (!auth) return; return json(response, 200, { teachers: all("SELECT DISTINCT u.id,u.display_name AS displayName FROM users u JOIN courses c ON c.teacher_id=u.id WHERE u.role='teacher' AND u.access_state='active' AND c.class_level=? ORDER BY u.display_name", auth.user.classLevel) }) }
    if (request.method === 'POST' && path === '/api/chat/conversations') { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const body = await readJson(request); let studentId = auth.user.role === 'student' ? auth.user.id : String(body.studentId || ''); let teacherId = body.teacherId ? String(body.teacherId) : null; const student = one("SELECT id,class_level FROM users WHERE id=? AND role='student' AND access_state='active'", studentId); if (!student) return json(response, 404, { error: 'Student not found.' }); if (auth.user.role === 'teacher') { teacherId = auth.user.id; if (!one('SELECT 1 FROM courses WHERE teacher_id=? AND class_level=?', auth.user.id, student.class_level)) return json(response, 403, { error: 'You are not assigned to this student’s class.' }) } if (teacherId && !one("SELECT id FROM users WHERE id=? AND role='teacher' AND access_state='active'", teacherId)) return json(response, 400, { error: 'Choose a valid teacher.' }); if (auth.user.role === 'student' && teacherId && !one('SELECT 1 FROM courses WHERE teacher_id=? AND class_level=?', teacherId, student.class_level)) return json(response, 403, { error: 'That teacher is not assigned to your class.' }); let conversation = one('SELECT * FROM conversations WHERE student_id=? AND teacher_id IS ?', studentId, teacherId); if (!conversation) { const timestamp = now(); conversation = { id: id(), student_id: studentId, teacher_id: teacherId, created_at: timestamp, updated_at: timestamp }; transaction(() => { run('INSERT INTO conversations VALUES (?,?,?,?,?)', conversation.id, studentId, teacherId, timestamp, timestamp); [studentId, teacherId].filter(Boolean).forEach((userId) => run('INSERT INTO conversation_participants VALUES (?,?)', conversation.id, userId)) }) }; return json(response, 201, { conversation: { id: conversation.id } }) }
    if (request.method === 'GET' && /^\/api\/chat\/conversations\/[^/]+\/messages$/.test(path)) { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const conversation = one('SELECT * FROM conversations WHERE id=?', path.split('/')[4]); if (!conversation || !canUseConversation(auth.user, conversation)) return json(response, 404, { error: 'Conversation not found.' }); const timestamp = now(); run('UPDATE messages SET delivered_at=COALESCE(delivered_at,?) WHERE conversation_id=? AND sender_id<>?', timestamp, conversation.id, auth.user.id); run('UPDATE messages SET read_at=? WHERE conversation_id=? AND sender_id<>? AND read_at IS NULL', timestamp, conversation.id, auth.user.id); return json(response, 200, { messages: all('SELECT m.id,m.sender_id AS senderId,m.body,m.created_at AS createdAt,m.delivered_at AS deliveredAt,m.read_at AS readAt,u.display_name AS senderName FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=? ORDER BY m.created_at', conversation.id) }) }
    if (request.method === 'POST' && /^\/api\/chat\/conversations\/[^/]+\/messages$/.test(path)) { const auth = requireRole(request, response, ['student','teacher','admin']); if (!auth) return; const conversation = one('SELECT * FROM conversations WHERE id=?', path.split('/')[4]); const body = await readJson(request); const message = String(body.body || '').trim(); if (!conversation || !canUseConversation(auth.user, conversation)) return json(response, 404, { error: 'Conversation not found.' }); if (!message || message.length > 2000) return json(response, 400, { error: 'Messages must be between 1 and 2000 characters.' }); const timestamp = now(); const messageId = id(); transaction(() => { run('INSERT INTO messages (id,conversation_id,sender_id,body,created_at,read_at,delivered_at) VALUES (?,?,?,?,?,?,?)', messageId, conversation.id, auth.user.id, message, timestamp, null, null); run('UPDATE conversations SET updated_at=? WHERE id=?', timestamp, conversation.id) }); return json(response, 201, { message: { id: messageId, body: message, senderId: auth.user.id, createdAt: timestamp, deliveryState: 'sent' } }) }
    if (request.method === 'GET' && path === '/api/student/lessons') { const auth = requireRole(request, response, ['student']); if (!auth) return; const lessons = all(`SELECT l.id,l.title,l.description,l.content,l.video_label AS videoLabel,l.notes_label AS notesLabel,l.material_label AS materialLabel,l.video_url AS videoUrl,l.notes_url AS notesUrl,l.material_url AS materialUrl,c.id AS courseId,c.title AS courseTitle,c.subject,ch.title AS chapterTitle,COALESCE(lp.status,'not_started') AS progressStatus FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE c.published=1 AND c.class_level=? AND l.status='published' AND (NOT EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id) OR EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id AND la.student_id=?)) ORDER BY c.subject,ch.position,l.position`, auth.user.id, auth.user.classLevel, auth.user.id); return json(response, 200, { lessons }) }
    if (request.method === 'GET' && /^\/api\/student\/lessons\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['student']); if (!auth) return; const lessonId = path.split('/')[4]; const lesson = one(`SELECT l.id,l.title,l.description,l.content,l.video_label AS videoLabel,l.notes_label AS notesLabel,l.material_label AS materialLabel,l.video_url AS videoUrl,l.notes_url AS notesUrl,l.material_url AS materialUrl,c.id AS courseId,c.title AS courseTitle,c.subject,ch.title AS chapterTitle,COALESCE(lp.status,'not_started') AS progressStatus FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.id=? AND c.published=1 AND c.class_level=? AND l.status='published' AND (NOT EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id) OR EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id AND la.student_id=?))`, auth.user.id, lessonId, auth.user.classLevel, auth.user.id); return lesson ? json(response, 200, { lesson }) : json(response, 404, { error: 'Lesson not found.' }) }
    if (request.method === 'PATCH' && /^\/api\/student\/lessons\/[^/]+\/progress$/.test(path)) { const auth = requireRole(request, response, ['student']); if (!auth) return; const lessonId = path.split('/')[4]; const body = await readJson(request); const status = body.status === 'completed' ? 'completed' : body.status === 'not_started' ? 'not_started' : null; if (!status) return json(response, 400, { error: 'Invalid lesson progress status.' }); const lesson = one(`SELECT l.id FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE l.id=? AND c.published=1 AND c.class_level=? AND l.status='published' AND (NOT EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id) OR EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id AND la.student_id=?))`, lessonId, auth.user.classLevel, auth.user.id); if (!lesson) return json(response, 404, { error: 'Lesson not found.' }); run(`INSERT INTO lesson_progress (user_id,lesson_id,status,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id,lesson_id) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at`, auth.user.id, lessonId, status, now()); return json(response, 200, { ok: true, status }) }
    if (request.method === 'GET' && path === '/api/security/sessions') { const auth = requireRole(request, response, ['student', 'teacher', 'admin']); if (!auth) return; return json(response, 200, { sessions: all('SELECT id,device_label AS deviceLabel,created_at AS createdAt,last_active_at AS lastActiveAt,expires_at AS expiresAt FROM sessions WHERE user_id=? AND revoked_at IS NULL ORDER BY last_active_at DESC', auth.user.id), notice: 'Only security-relevant device information is stored. Precise location is not collected.' }) }
    if (request.method === 'POST' && path.startsWith('/api/security/sessions/') && path.endsWith('/revoke')) { const auth = requireRole(request, response, ['student', 'teacher', 'admin']); if (!auth) return; const sessionId = path.split('/')[4]; const session = one('SELECT id FROM sessions WHERE id=? AND user_id=? AND revoked_at IS NULL', sessionId, auth.user.id); if (!session) return json(response, 404, { error: 'Session not found.' }); run('UPDATE sessions SET revoked_at=?,revoked_by=?,revoke_reason=? WHERE id=?', now(), auth.user.id, 'user_revoke', sessionId); event(auth.user.id, 'session_revoked', request, 'Session revoked by account owner', sessionId); return json(response, 200, { ok: true }) }
    if (request.method === 'GET' && path === '/api/admin/users') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const role = url.searchParams.get('role'); const state = url.searchParams.get('state'); if (role && !['student','teacher'].includes(role)) return json(response, 400, { error: 'Invalid role.' }); if (state && !['active','disabled'].includes(state)) return json(response, 400, { error: 'Invalid access state.' }); return json(response, 200, { users: all(`SELECT id,email,display_name AS displayName,role,class_level AS classLevel,access_state AS accessState,created_at AS createdAt FROM users WHERE role IN ('student','teacher') ${role ? 'AND role=?' : ''} ${state ? 'AND access_state=?' : ''} ORDER BY role,display_name`, ...(role ? [role] : []), ...(state ? [state] : [])) }) }
    if (request.method === 'PATCH' && /^\/api\/admin\/users\/[^/]+\/access$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const userId = path.split('/')[4]; const body = await readJson(request); if (!['active','disabled'].includes(body.accessState)) return json(response, 400, { error: 'Choose Active or Deactivated.' }); const managed = one("SELECT id FROM users WHERE id=? AND role IN ('student','teacher')", userId); if (!managed) return json(response, 404, { error: 'User not found.' }); run('UPDATE users SET access_state=?,updated_at=? WHERE id=?', body.accessState, now(), userId); if (body.accessState === 'disabled') run("UPDATE sessions SET revoked_at=?,revoked_by=?,revoke_reason='admin_deactivate' WHERE user_id=? AND revoked_at IS NULL", now(), auth.user.id, userId); event(userId, body.accessState === 'disabled' ? 'access_deactivated' : 'access_reactivated', request, `Access ${body.accessState} by admin`); return json(response, 200, { ok: true }) }
    if (request.method === 'DELETE' && /^\/api\/admin\/users\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const userId = path.split('/')[4]; const managed = one("SELECT id FROM users WHERE id=? AND role IN ('student','teacher')", userId); if (!managed) return json(response, 404, { error: 'User not found.' }); const assets = all('SELECT stored_filename FROM lesson_assets WHERE uploader_id=?', userId); const result = run("DELETE FROM users WHERE id=? AND role IN ('student','teacher')", userId); await Promise.all(assets.map((asset) => unlink(resolve(uploadDirectory, asset.stored_filename)).catch(() => undefined))); return result.changes ? json(response, 200, { ok: true }) : json(response, 404, { error: 'User not found.' }) }
    if (request.method === 'GET' && path === '/api/admin/students') { const auth = requireRole(request, response, ['admin']); if (!auth) return; return json(response, 200, { students: all("SELECT id,email,display_name AS displayName,class_level AS classLevel,access_state AS accessState,created_at AS createdAt FROM users WHERE role='student' ORDER BY created_at DESC") }) }
    if (request.method === 'GET' && path === '/api/admin/student-progress') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const classLevel = Number(url.searchParams.get('classLevel')); if (url.searchParams.has('classLevel') && ![8,9,10].includes(classLevel)) return json(response, 400, { error: 'Choose a class.' }); const students = all(`SELECT u.id,u.email,u.display_name AS displayName,u.class_level AS classLevel,u.access_state AS accessState,(SELECT COUNT(*) FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE c.class_level=u.class_level AND c.published=1 AND l.status='published' AND (NOT EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id) OR EXISTS (SELECT 1 FROM lesson_assignments la WHERE la.lesson_id=l.id AND la.student_id=u.id))) AS availableLessons,(SELECT COUNT(*) FROM lesson_progress lp WHERE lp.user_id=u.id AND lp.status='completed') AS completedLessons FROM users u WHERE u.role='student' ${[8,9,10].includes(classLevel) ? 'AND u.class_level=?' : ''} ORDER BY u.class_level,u.display_name`, ...([8,9,10].includes(classLevel) ? [classLevel] : [])).map((student) => ({ ...student, remainingLessons: Math.max(0, Number(student.availableLessons) - Number(student.completedLessons)), progressPercent: Number(student.availableLessons) ? Math.round(Number(student.completedLessons) * 100 / Number(student.availableLessons)) : 0 })); return json(response, 200, { students }) }
    if (request.method === 'GET' && path === '/api/admin/class-overview') { const auth = requireRole(request, response, ['admin']); if (!auth) return; const classes = [8,9,10].map((classLevel) => ({ classLevel, activeStudents: Number(one("SELECT COUNT(*) AS count FROM users WHERE role='student' AND access_state='active' AND class_level=?", classLevel).count), totalLessons: Number(one('SELECT COUNT(*) AS count FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE c.class_level=?', classLevel).count), publishedLessons: Number(one("SELECT COUNT(*) AS count FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE c.class_level=? AND c.published=1 AND l.status='published'", classLevel).count) })); return json(response, 200, { classes }) }
    if (request.method === 'PATCH' && /^\/api\/admin\/students\/[^/]+\/access$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const studentId = path.split('/')[4]; const body = await readJson(request); if (!['active', 'denied'].includes(body.accessState)) return json(response, 400, { error: 'Invalid access state.' }); const student = one("SELECT id FROM users WHERE id=? AND role='student'", studentId); if (!student) return json(response, 404, { error: 'Student not found.' }); run('UPDATE users SET access_state=?,updated_at=? WHERE id=?', body.accessState, now(), studentId); if (body.accessState === 'denied') run("UPDATE sessions SET revoked_at=?,revoked_by=?,revoke_reason='security_response' WHERE user_id=? AND revoked_at IS NULL", now(), auth.user.id, studentId); event(studentId, body.accessState === 'denied' ? 'access_denied' : 'access_restored', request, `Access ${body.accessState} by admin`); return json(response, 200, { ok: true }) }
    if (request.method === 'POST' && /^\/api\/admin\/students\/[^/]+\/password-reset$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const studentId = path.split('/')[4]; const student = one("SELECT id FROM users WHERE id=? AND role='student'", studentId); if (!student) return json(response, 404, { error: 'Student not found.' }); createPasswordReset(student.id, request, auth.user.id); return json(response, 200, { message: 'Password reset initiated for this student.' }) }
    if (request.method === 'POST' && /^\/api\/admin\/students\/[^/]+\/revoke-sessions$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const studentId = path.split('/')[4]; const result = run("UPDATE sessions SET revoked_at=?,revoked_by=?,revoke_reason='admin_revoke_all' WHERE user_id=? AND revoked_at IS NULL", now(), auth.user.id, studentId); event(studentId, 'session_revoked', request, 'All sessions revoked by admin'); return json(response, 200, { revoked: Number(result.changes) }) }
    if (request.method === 'DELETE' && /^\/api\/admin\/students\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['admin']); if (!auth) return; const studentId = path.split('/')[4]; const result = run("DELETE FROM users WHERE id=? AND role='student'", studentId); return result.changes ? json(response, 200, { ok: true }) : json(response, 404, { error: 'Student not found.' }) }
    if (request.method === 'GET' && path === '/api/admin/sessions') { const auth = requireRole(request, response, ['admin']); if (!auth) return; return json(response, 200, { sessions: all(`SELECT s.id,s.device_label AS deviceLabel,s.created_at AS createdAt,s.last_active_at AS lastActiveAt,s.expires_at AS expiresAt,u.display_name AS displayName,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.revoked_at IS NULL ORDER BY s.last_active_at DESC LIMIT 100`) }) }
    if (request.method === 'GET' && path === '/api/teacher/students') { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const classLevel = Number(url.searchParams.get('classLevel')); if (![8,9,10].includes(classLevel)) return json(response, 400, { error: 'Choose a class.' }); return json(response, 200, { students: all("SELECT id,display_name AS displayName,class_level AS classLevel FROM users WHERE role='student' AND access_state='active' AND class_level=? ORDER BY display_name", classLevel) }) }
    if (request.method === 'PATCH' && /^\/api\/teacher\/lessons\/[^/]+\/resources$/.test(path)) { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const lessonId = path.split('/')[4]; const lesson = one(`SELECT l.id,c.teacher_id FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE l.id=?`, lessonId); if (!lesson || lesson.teacher_id !== auth.user.id) return json(response, 404, { error: 'Lesson not found.' }); const body = await readJson(request); run('UPDATE lessons SET video_url=?,notes_url=?,material_url=? WHERE id=?', String(body.videoUrl || ''), String(body.notesUrl || ''), String(body.materialUrl || ''), lessonId); return json(response, 200, { ok: true }) }
    if (request.method === 'GET' && path === '/api/teacher/lessons') { const auth = requireRole(request, response, ['teacher']); if (!auth) return; return json(response, 200, { lessons: all(`SELECT l.id,l.title,l.description,l.content,l.status,l.video_label AS videoLabel,l.notes_label AS notesLabel,l.material_label AS materialLabel,l.video_url AS videoUrl,l.notes_url AS notesUrl,l.material_url AS materialUrl,c.title AS courseTitle,c.subject,c.class_level AS classLevel,ch.title AS chapterTitle,COALESCE(json_group_array(la.student_id) FILTER (WHERE la.student_id IS NOT NULL),'[]') AS assignedStudentIds FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id LEFT JOIN lesson_assignments la ON la.lesson_id=l.id WHERE c.teacher_id=? GROUP BY l.id ORDER BY l.created_at DESC`, auth.user.id) }) }
    if (request.method === 'POST' && path === '/api/teacher/lessons') { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const body = await readJson(request); const classLevel = Number(body.classLevel); const assignedStudentIds = Array.isArray(body.assignedStudentIds) ? body.assignedStudentIds : []; const status = body.status === 'published' ? 'published' : 'draft'; if (!['mathematics','science','english','sst'].includes(body.subject) || ![8,9,10].includes(classLevel) || !String(body.title || '').trim()) return json(response, 400, { error: 'Choose a subject, class, and lesson title.' }); const validAssignments = all(`SELECT id FROM users WHERE role='student' AND access_state='active' AND class_level=? AND id IN (${assignedStudentIds.map(() => '?').join(',') || "''"})`, classLevel, ...assignedStudentIds).map((student) => student.id); if (validAssignments.length !== assignedStudentIds.length) return json(response, 400, { error: 'Assigned students must be active students in the selected class.' }); const timestamp = now(); const courseTitle = String(body.courseTitle || `${body.subject} · Class ${classLevel}`).trim(); const existingCourse = one('SELECT id FROM courses WHERE teacher_id=? AND title=? AND subject=? AND class_level=?', auth.user.id, courseTitle, body.subject, classLevel); const courseId = existingCourse?.id || id(); const chapterId = id(); const lessonId = id(); transaction(() => { if (!existingCourse) run('INSERT INTO courses VALUES (?,?,?,?,?,?,?,?)', courseId, courseTitle, body.subject, classLevel, auth.user.id, String(body.courseDescription || 'Teacher-created course'), 1, timestamp); run('INSERT INTO chapters VALUES (?,?,?,?,?)', chapterId, courseId, String(body.chapterTitle || 'Teacher uploads'), String(body.chapterDescription || 'Lesson collection'), 1); run('INSERT INTO lessons (id,chapter_id,title,description,video_label,notes_label,material_label,content,status,position,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', lessonId, chapterId, String(body.title).trim(), String(body.description || ''), String(body.videoLabel || 'Video to be added'), String(body.notesLabel || 'Notes to be added'), String(body.materialLabel || 'Study material to be added'), String(body.content || ''), status, 1, timestamp); validAssignments.forEach((studentId) => run('INSERT INTO lesson_assignments VALUES (?,?)', lessonId, studentId)) }); return json(response, 201, { lesson: { id: lessonId } }) }
    if (request.method === 'PATCH' && /^\/api\/teacher\/lessons\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const lessonId = path.split('/')[4]; const lesson = one(`SELECT l.id,c.id AS course_id,c.teacher_id FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE l.id=?`, lessonId); if (!lesson || lesson.teacher_id !== auth.user.id) return json(response, 404, { error: 'Lesson not found.' }); const body = await readJson(request); const classLevel = Number(body.classLevel); const assignedStudentIds = Array.isArray(body.assignedStudentIds) ? body.assignedStudentIds : []; const status = body.status === 'published' ? 'published' : 'draft'; if (!['mathematics','science','english','sst'].includes(body.subject) || ![8,9,10].includes(classLevel) || !String(body.title || '').trim()) return json(response, 400, { error: 'Choose a subject, class, and lesson title.' }); const validAssignments = all(`SELECT id FROM users WHERE role='student' AND access_state='active' AND class_level=? AND id IN (${assignedStudentIds.map(() => '?').join(',') || "''"})`, classLevel, ...assignedStudentIds).map((student) => student.id); if (validAssignments.length !== assignedStudentIds.length) return json(response, 400, { error: 'Assigned students must be active students in the selected class.' }); transaction(() => { run('UPDATE lessons SET title=?,description=?,content=?,video_label=?,notes_label=?,material_label=?,status=? WHERE id=?', String(body.title).trim(), String(body.description || ''), String(body.content || ''), String(body.videoLabel || ''), String(body.notesLabel || ''), String(body.materialLabel || ''), status, lessonId); run('UPDATE courses SET subject=?,class_level=?,description=? WHERE id=?', body.subject, classLevel, String(body.courseDescription || 'Teacher-created course'), lesson.course_id); run('DELETE FROM lesson_assignments WHERE lesson_id=?', lessonId); validAssignments.forEach((studentId) => run('INSERT INTO lesson_assignments VALUES (?,?)', lessonId, studentId)); }); return json(response, 200, { ok: true }) }
    if (request.method === 'DELETE' && /^\/api\/teacher\/lessons\/[^/]+$/.test(path)) { const auth = requireRole(request, response, ['teacher']); if (!auth) return; const lessonId = path.split('/')[4]; const lesson = one(`SELECT l.id,c.id AS course_id,c.teacher_id FROM lessons l JOIN chapters ch ON ch.id=l.chapter_id JOIN courses c ON c.id=ch.course_id WHERE l.id=?`, lessonId); if (!lesson || lesson.teacher_id !== auth.user.id) return json(response, 404, { error: 'Lesson not found.' }); const assets = all('SELECT stored_filename FROM lesson_assets WHERE lesson_id=?', lessonId); const result = run('DELETE FROM lessons WHERE id=?', lessonId); if (!result.changes) return json(response, 404, { error: 'Lesson not found.' }); await Promise.all(assets.map((asset) => unlink(resolve(uploadDirectory, asset.stored_filename)).catch(() => undefined))); return json(response, 200, { ok: true }) }
    return json(response, 404, { error: 'Route not found.' })
  } catch (error) { if (process.env.NODE_ENV !== 'production') console.error(error); return json(response, 500, { error: 'The server could not complete this request.' }) }
}

async function serveFrontend(request, response) {
  if (!['GET', 'HEAD'].includes(request.method)) return json(response, 405, { error: 'Method not allowed.' })
  const pathname = decodeURIComponent(new URL(request.url, `http://${request.headers.host}`).pathname)
  const relativePath = pathname === '/' ? 'index.html' : pathname.replace(/^[/\\]+/, '')
  const candidate = resolve(distDirectory, relativePath)
  const safeCandidate = candidate === distDirectory || candidate.startsWith(`${distDirectory}${sep}`)
  const filePath = safeCandidate && existsSync(candidate) && (await stat(candidate)).isFile() ? candidate : resolve(distDirectory, 'index.html')
  if (!existsSync(filePath)) return json(response, 503, { error: 'Frontend build not found. Run npm run build before starting the production server.' })
  response.writeHead(200, { 'Content-Type': mimeTypes[extname(filePath).toLowerCase()] || 'application/octet-stream', 'Cache-Control': filePath.endsWith('index.html') ? 'no-cache' : 'public, max-age=31536000, immutable' })
  if (request.method === 'HEAD') return response.end()
  createReadStream(filePath).pipe(response)
}

async function application(request, response) {
  const path = new URL(request.url, `http://${request.headers.host}`).pathname
  if (path === '/api' || path.startsWith('/api/')) return route(request, response)
  return serveFrontend(request, response)
}

await bootstrapConfiguredAdmin()
await seedDemoAccounts()
createServer(application).listen(port, '0.0.0.0', () => console.log(`Tutorial Online Class listening on http://0.0.0.0:${port} using ${databasePath}${demoMode ? ' (demo accounts enabled)' : ''}`))
